[project]
name = "discpyth"
version = "0.1.0"
description = "DiscPyth is an unofficial wrapper in python for the official Discord API."
authors = [
    "arHSM <hanseungmin.ar@gmail.com>"
]
license = "MIT"
readme = "README.md"
python = "^3.6"
homepage = "https://github.com/DiscPyth/DiscPyth"
repository = "https://github.com/DiscPyth/DiscPyth"
#documentation = "https://github.com/DiscPyth/DiscPyth"


keywords = ["discord", "discord-api", "discord-bot", "REST", "websocket"]

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Topic :: Communications :: Chat",
    'Topic :: Internet',
    'Topic :: Software Development :: Libraries',
    'Topic :: Software Development :: Libraries :: Python Modules',
    'Topic :: Utilities',
    "License :: OSI Approved :: MIT License",
]

# Requirements
[dependencies]
anyio = "*"
httpx = "*"
wsproto = "*"

[dev-dependencies]
black = "*"
isort="*"
pylint = "*"
flake8 = "*"
mypy = "*"

[tool.black]
line-length = 79

[tool.isort]
profile = 'black'

[tool.pylint.messages_control]
# C0330: Wrong hanging indentation before block (add 4 spaces)
# C0326: Bad whitespace
# C0301: Line too long
# R0903: Too few public methods (n/2)
# W1203: logging-fstring-interpolation
# C0116: Missing function or method docstring
# C0115: Missing class docstring
# C0114: Missing module docstring
# W0511: TODO warnings, (fix-me)
disable = "C0330, C0326, C0301, R0903, W1203, C0116, C0115, C0114, W0511"

[tool.pylint.format]
max-line-length = "79"

[build-system]
requires = [
    "setuptools>=42",
    "wheel"
]
build-backend = "setuptools.build_meta"