name: Miscellaneous
description: >-
  Miscellaneous report aka a topic I forgot to add or maybe its really
  miscellaneous :^)
title: 'Misc : '
body:
  - type: textarea
    id: misc_body
    attributes:
      label: Body of the Report -
      description: Think it of as a blank issue... and type it out
      placeholder: Dics and Dics wow I forgot how to spell Disks in the making of DiscPyth...