from .eventhandlers import EventHandler

from .structs import (  # isort: skip
    Ready,
    Resumed,
    Reconnect,
    InvalidSession,
    ChannelCreate,
    ChannelDelete,
    ChannelPinsUpdate,
    ChannelUpdate,
    ThreadCreate,
    ThreadDelete,
    ThreadListSync,
    ThreadMembersUpdate,
    ThreadMemberUpdate,
    ThreadUpdate,
    GuildCreate,
    GuildDelete,
    GuildUpdate,
    GuildBanAdd,
    GuildBanRemove,
    GuildEmojisUpdate,
    GuildStickersUpdate,
    GuildIntegrationsUpdate,
    GuildMemberAdd,
    GuildMemberRemove,
    GuildMemberUpdate,
    GuildMembersChunk,
    GuildRoleCreate,
    GuildRoleDelete,
    GuildRoleUpdate,
    GuildScheduledEventCreate,
    GuildScheduledEventDelete,
    GuildScheduledEventUpdate,
    GuildScheduledEventUserAdd,
    GuildScheduledEventUserRemove,
    IntegrationCreate,
    IntegrationDelete,
    IntegrationUpdate,
    InteractionCreate,
    InviteCreate,
    InviteDelete,
    MessageCreate,
    MessageDelete,
    MessageUpdate,
    MessageDeleteBulk,
    MessageReactionAdd,
    MessageReactionRemove,
    MessageReactionRemoveAll,
    MessageReactionRemoveEmoji,
    PresenceUpdate,
    StageInstanceCreate,
    StageInstanceDelete,
    StageInstanceUpdate,
    TypingStart,
    UserUpdate,
    VoiceServerUpdate,
    VoiceStateUpdate,
    WebhooksUpdate,
)


class EventsHandler:
    __slots__ = {"event_map", "valid_events"}

    def __init__(self):
        # fmt: off
        self.event_map = {
            "READY"                             : EventHandler(Ready),
            "RESUMED"                           : EventHandler(Resumed),
            "RECONNECT"                         : EventHandler(Reconnect),
            "INVALID_SESSION"                   : EventHandler(InvalidSession),
            "CHANNEL_CREATE"                    : EventHandler(ChannelCreate),
            "CHANNEL_DELETE"                    : EventHandler(ChannelDelete),
            "CHANNEL_PINS_UPDATE"               : EventHandler(ChannelPinsUpdate),
            "CHANNEL_UPDATE"                    : EventHandler(ChannelUpdate),
            "THREAD_CREATE"                     : EventHandler(ThreadCreate),
            "THREAD_DELETE"                     : EventHandler(ThreadDelete),
            "THREAD_LIST_SYNC"                  : EventHandler(ThreadListSync),
            "THREAD_MEMBERS_UPDATE"             : EventHandler(ThreadMembersUpdate),
            "THREAD_MEMBER_UPDATE"              : EventHandler(ThreadMemberUpdate),
            "THREAD_UPDATE"                     : EventHandler(ThreadUpdate),
            "GUILD_CREATE"                      : EventHandler(GuildCreate),
            "GUILD_DELETE"                      : EventHandler(GuildDelete),
            "GUILD_UPDATE"                      : EventHandler(GuildUpdate),
            "GUILD_BAN_ADD"                     : EventHandler(GuildBanAdd),
            "GUILD_BAN_REMOVE"                  : EventHandler(GuildBanRemove),
            "GUILD_EMOJIS_UPDATE"               : EventHandler(GuildEmojisUpdate),
            "GUILD_STICKERS_UPDATE"             : EventHandler(GuildStickersUpdate),
            "GUILD_INTEGRATIONS_UPDATE"         : EventHandler(GuildIntegrationsUpdate),
            "GUILD_MEMBER_ADD"                  : EventHandler(GuildMemberAdd),
            "GUILD_MEMBER_REMOVE"               : EventHandler(GuildMemberRemove),
            "GUILD_MEMBER_UPDATE"               : EventHandler(GuildMemberUpdate),
            "GUILD_MEMBERS_CHUNK"               : EventHandler(GuildMembersChunk),
            "GUILD_ROLE_CREATE"                 : EventHandler(GuildRoleCreate),
            "GUILD_ROLE_DELETE"                 : EventHandler(GuildRoleDelete),
            "GUILD_ROLE_UPDATE"                 : EventHandler(GuildRoleUpdate),
            "GUILD_SCHEDULED_EVENT_CREATE"      : EventHandler(GuildScheduledEventCreate),
            "GUILD_SCHEDULED_EVENT_DELETE"      : EventHandler(GuildScheduledEventDelete),
            "GUILD_SCHEDULED_EVENT_UPDATE"      : EventHandler(GuildScheduledEventUpdate),
            "GUILD_SCHEDULED_EVENT_USER_ADD"    : EventHandler(GuildScheduledEventUserAdd),
            "GUILD_SCHEDULED_EVENT_USER_REMOVE" : EventHandler(GuildScheduledEventUserRemove),
            "INTEGRATION_CREATE"                : EventHandler(IntegrationCreate),
            "INTEGRATION_DELETE"                : EventHandler(IntegrationDelete),
            "INTEGRATION_UPDATE"                : EventHandler(IntegrationUpdate),
            "INTERACTION_CREATE"                : EventHandler(InteractionCreate),
            "INVITE_CREATE"                     : EventHandler(InviteCreate),
            "INVITE_DELETE"                     : EventHandler(InviteDelete),
            "MESSAGE_CREATE"                    : EventHandler(MessageCreate),
            "MESSAGE_DELETE"                    : EventHandler(MessageDelete),
            "MESSAGE_UPDATE"                    : EventHandler(MessageUpdate),
            "MESSAGE_DELETE_BULK"               : EventHandler(MessageDeleteBulk),
            "MESSAGE_REACTION_ADD"              : EventHandler(MessageReactionAdd),
            "MESSAGE_REACTION_REMOVE"           : EventHandler(MessageReactionRemove),
            "MESSAGE_REACTION_REMOVE_ALL"       : EventHandler(MessageReactionRemoveAll),
            "MESSAGE_REACTION_REMOVE_EMOJI"     : EventHandler(MessageReactionRemoveEmoji),
            "PRESENCE_UPDATE"                   : EventHandler(PresenceUpdate),
            "STAGE_INSTANCE_CREATE"             : EventHandler(StageInstanceCreate),
            "STAGE_INSTANCE_DELETE"             : EventHandler(StageInstanceDelete),
            "STAGE_INSTANCE_UPDATE"             : EventHandler(StageInstanceUpdate),
            "TYPING_START"                      : EventHandler(TypingStart),
            "USER_UPDATE"                       : EventHandler(UserUpdate),
            "VOICE_SERVER_UPDATE"               : EventHandler(VoiceServerUpdate),
            "VOICE_STATE_UPDATE"                : EventHandler(VoiceStateUpdate),
            "WEBHOOKS_UPDATE"                   : EventHandler(WebhooksUpdate),
        }
        # fmt: on
        self.valid_events = [
            "READY",
            "RESUMED",
            "RECONNECT",
            "INVALID_SESSION",
            "GUILD_MEMBERS_CHUNK",
            "INTERACTION_CREATE",
            "USER_UPDATE",
            "VOICE_SERVER_UPDATE",
        ]
